/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4aPch0x9XMR
 */
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { TabsTrigger, TabsList, TabsContent, Tabs } from '@/components/ui/tabs'
import { Todo } from './todo'
import { shell } from '@/shell/shell'
import { useState } from 'react'

export function Todos() {
  const all = shell.useTodosByFilter('all')
  const active = shell.useTodosByFilter('active')
  const done = shell.useTodosByFilter('done')

  const [newTodoText, setNewTodoText] = useState('')

  return (
    <div className="flex flex-col items-center pt-[100px] min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md">
        <div className="bg-white dark:bg-gray-800 shadow rounded-lg p-6">
          <div className="mb-4">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
              Todo App
            </h2>
            <p className="text-gray-600 dark:text-gray-400">
              Manage your tasks efficiently
            </p>
          </div>
          <div className="mb-4">
            <form
              className="flex space-x-2"
              onSubmit={(e) => {
                e.preventDefault()
                shell.addTodo(newTodoText)
                setNewTodoText('')
              }}
            >
              <Input
                id="new-task"
                placeholder="New task"
                value={newTodoText}
                onChange={(e) => setNewTodoText(e.target.value)}
              />
              <Button type="submit">Add Todo</Button>
            </form>
          </div>
          <Tabs className="w-full" defaultValue="all">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="all">All</TabsTrigger>
              <TabsTrigger value="active">Active</TabsTrigger>
              <TabsTrigger value="done">Done</TabsTrigger>
            </TabsList>
            <TabsContent value="all">
              {all.map((todo) => (
                <Todo key={todo.id} id={todo.id} />
              ))}
            </TabsContent>
            <TabsContent value="active">
              {active.map((todo) => (
                <Todo key={todo.id} id={todo.id} />
              ))}
            </TabsContent>
            <TabsContent value="done">
              {done.map((todo) => (
                <Todo key={todo.id} id={todo.id} />
              ))}
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  )
}
